### ISSUE TITLE
Support for source.c++.11

### ISSUE THREAD

**Issue by tillt** [rampage644/sublime-rtags#23]
The plugin currently uses hardcoded file-types for determining if it should invoke `rc` on changes etc. Users that have extended source type highlighting for C++11 (source.c++.11), this will prevent sublime-rtags from functioning. 

Additionally, RTags seems to be ObjectiveC compatible, hence it should be allowed to use the plugin on such files.

**Comment by tillt** [comment]
Created a PR: https://github.com/rampage644/sublime-rtags/pull/24

**Comment by rampage644** [comment]
Closed with #24
