### ISSUE TITLE
Navigation fails as rc returns relative paths.

### ISSUE THREAD

**Issue by tillt** [rampage644/sublime-rtags#25]
I have a project that does not allow proper symbol navigation (think `rtags_location`, `-f`) unless an absolute path was returned. I am entirely unsure on why this is a problem for me and not everyone else. 

The problem:

```
$ /usr/local/bin/rc --silent-query -f /Users/till/Development/mesos-private/3rdparty/libprocess/3rdparty/stout/tests/os_tests.cpp:103:11
3rdparty/libprocess/3rdparty/stout/include/stout/hashset.hpp:34:7:	class hashset : public boost::unordered_set<Elem, Hash, Equal>
```

The only fix I found was prepending the rc call with `--absolute-path`.

```
$ /usr/local/bin/rc --silent-query --absolute-path -f /Users/till/Development/mesos-private/3rdparty/libprocess/3rdparty/stout/tests/os_tests.cpp:103:11 
/Users/till/Development/mesos-private/3rdparty/libprocess/3rdparty/stout/include/stout/hashset.hpp:34:7:	class hashset : public boost::unordered_set<Elem, Hash, Equal>
```

The plugin however does only allow single switches within the keyboard configuration, so I can not add that additional switch this way.

I did prepare an updated version of the plugin for allowing the needed switch addition - https://github.com/tillt/sublime-rtags/commit/344e1404017ae07b50ca2c193b601582d3b8a9d4 - again, I am unsure if this is the right way to fix the problem. In any case, here is my fix for your consideration. Will create a PR if this was a feasible solution.

**Comment by rampage644** [comment]
Could you please create PR so i can merge it? Code itself looks good and i have no objections with supporting multiple switches anyway.

**Comment by Wintaru** [comment]
I'm having the same problem, although trying to make the same changes as tillt did locally give me an error:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
TypeError: run() missing 1 required positional argument: 'switch'

**Comment by tillt** [comment]
Sorry for the delay, I was crazy busy...

Here it is; https://github.com/rampage644/sublime-rtags/pull/26

Thanks for considering this change!
