### ISSUE TITLE
Publish latest version to Package Control

### ISSUE THREAD

**Issue by jaytiar** [rampage644/sublime-rtags#27]
Hi. Plugin looks great - thanks for developing!

However, I need the fixes that have been made most recently to allow absolute paths, but it looks like you have not tagged a new version since October '14 so Package Control is still installing the old version from then without the most recent fixes.

Could you please publish the latest version so PackageControl picks it up?

Also, you need to merge the key-bindings changes into the (Linux) and (Windows) files - they've only been applied to the (OSX) keymap at the moment.

Thanks!

**Comment by tillt** [comment]
Sorry for not fixing up the Linux and Windows keymaps - that was my omission when adding the `--absolute-path` switch.

I am currently trying to fix the `cursor_command` aka `--symbol-info/-U` - a promising fix is already available in my fork - will send a PR once I am fully satisfied with the results. See https://github.com/tillt/sublime-rtags for more. That fork also contains fixed keymaps for all platforms.

For the publishing of the latest version, that seems to be a task for the project owner - @rampage644 what do you think?

**Comment by rampage644** [comment]
@tillt, good job!

Yes, I'll update version once you've done with you PR. Unfortunately, i've switched from sublime and don't do any development with it right now.

**Comment by tillt** [comment]
@rampage644 @jaytiar the PR (https://github.com/rampage644/sublime-rtags/pull/30) is up, please give it a shot.

**Comment by rampage644** [comment]
@tillt, @jaytiar. Latest version is published.
