### ISSUE TITLE
Find-references-at-point support

### ISSUE THREAD

**Issue by wastedepository** [rampage644/sublime-rtags#34]
The two main features of rtags that I use are (by their Emacs function names) find-symbol-at-point and find-references-at-point. Is there a way to do find-references-at-point via sublime-rtags? I couldn't find it by a quick examination of the Python code.

(The Emacs find-symbol function, taking a name as input, would also be quite useful, as it is more powerful than Sublime Text's goto-definition, which can't deal with variables. The find-references function is also very useful, as are the current-dir and current-file versions of these functions. However, find-references-at-point is the most important of these unimplemented functions, IMO.)

**Comment by tillt** [comment]
You mean "Find usages - Ctrl+Shift+u" it seems, no?

You move to a symbol, hit Ctrl+Shift+u and as a result you will see a window listing all references of that object within your project.

**Comment by tillt** [comment]
Suggesting to close this issue as the OP was not showing further actions and hints a possible user error.
